### ISSUE TITLE
1.21 Client Side Stuttering

### ISSUE THREAD

**Issue by Logan9312** [moritz-htk/better-mcdonalds-mod#1]
I am not sure why or how, but when I added this mod to my server, it causes client side lag stuttering spikes every couple seconds.

**Comment by moritz-htk** [comment]
Okay, thanks for your message. I'll try to replicate it. I have a few questions. Which modloader are you using and with which version? What other mods do you use? Please check your logs for any errors.

**Comment by Logan9312** [comment]
False alarm, my bad. After some testing it may have been another mod that was coincidentally enabled when I was testing this.
