### ISSUE TITLE
Using knife on a raw beef crashes the game

### ISSUE THREAD

**Issue by Tanjiraaaaa** [moritz-htk/better-mcdonalds-mod#2]
It is exactly how it sounds in the title
When I try to use the knife and the raw beef in the crafting table, it crashes the game.
I am on 1.20.6

**Comment by Tanjiraaaaa** [comment]
Update: When I got back on the world, the knife disappeared from my inventory as well. However, the raw beef is still there.

**Comment by moritz-htk** [comment]
Okay, thanks for your message. I have a few questions. Which mod loader are you using and with which version? Please check your logs for the error message.

**Comment by moritz-htk** [comment]
I've released a new version that should fix the crash. Have a good day!
